package mcp

import "github.com/mark3labs/mcp-go/mcp"

// Tool definitions for all 11 Moss MCP tools.
// Addressing params (id, workspace, name) are all optional in schema;
// "exactly one addressing mode" rule is enforced by handlers via ops.ValidateAddress().

var storeToolDef = mcp.NewTool("moss.store",
	mcp.WithDescription("Store a new context capsule. Creates a distilled context snapshot for AI session handoffs."),
	mcp.WithString("capsule_text",
		mcp.Required(),
		mcp.Description("The capsule content with 6 required sections: Objective, Status, Decisions, Next actions, Key locations, Open questions"),
	),
	mcp.WithString("workspace",
		mcp.Description("Namespace for the capsule (default: 'default')"),
	),
	mcp.WithString("name",
		mcp.Description("Unique handle within workspace. Omit for unnamed capsules."),
	),
	mcp.WithString("title",
		mcp.Description("Human-readable title. Defaults to name if not provided."),
	),
	mcp.WithArray("tags",
		mcp.Description("Tags for categorization"),
		mcp.WithStringItems(),
	),
	mcp.WithString("source",
		mcp.Description("Origin identifier (e.g., session ID, file path)"),
	),
	mcp.WithString("mode",
		mcp.Description("Collision behavior: 'error' (default) fails on name collision, 'replace' overwrites existing"),
		mcp.Enum("error", "replace"),
	),
	mcp.WithBoolean("allow_thin",
		mcp.Description("If true, skip section validation. Use sparingly for quick notes."),
	),
)

var fetchToolDef = mcp.NewTool("moss.fetch",
	mcp.WithDescription("Fetch a single capsule by ID or name. Use exactly one addressing mode: id OR (workspace+name)."),
	mcp.WithString("id",
		mcp.Description("Capsule ID (ULID). Mutually exclusive with workspace+name."),
	),
	mcp.WithString("workspace",
		mcp.Description("Workspace namespace. Required with name."),
	),
	mcp.WithString("name",
		mcp.Description("Capsule name within workspace."),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules in lookup"),
	),
	mcp.WithBoolean("include_text",
		mcp.Description("Include capsule_text in response (default: true)"),
	),
)

var fetchManyToolDef = mcp.NewTool("moss.fetch_many",
	mcp.WithDescription("Fetch multiple capsules in a single request. Returns partial success with items and errors arrays."),
	mcp.WithArray("items",
		mcp.Required(),
		mcp.Description("Array of capsule references. Each item uses id OR (workspace+name)."),
		mcp.Items(map[string]any{
			"type": "object",
			"properties": map[string]any{
				"id":        map[string]any{"type": "string", "description": "Capsule ID (ULID)"},
				"workspace": map[string]any{"type": "string", "description": "Workspace namespace"},
				"name":      map[string]any{"type": "string", "description": "Capsule name"},
			},
		}),
	),
	mcp.WithBoolean("include_text",
		mcp.Description("Include capsule_text in response (default: true)"),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules in lookup"),
	),
)

var updateToolDef = mcp.NewTool("moss.update",
	mcp.WithDescription("Update an existing capsule. Address by id OR (workspace+name). At least one editable field required."),
	mcp.WithString("id",
		mcp.Description("Capsule ID (ULID). Mutually exclusive with workspace+name."),
	),
	mcp.WithString("workspace",
		mcp.Description("Workspace namespace. Required with name."),
	),
	mcp.WithString("name",
		mcp.Description("Capsule name within workspace."),
	),
	mcp.WithString("capsule_text",
		mcp.Description("New capsule content (validates sections unless allow_thin)"),
	),
	mcp.WithString("title",
		mcp.Description("New title"),
	),
	mcp.WithArray("tags",
		mcp.Description("New tags (replaces existing)"),
		mcp.WithStringItems(),
	),
	mcp.WithString("source",
		mcp.Description("New source identifier"),
	),
	mcp.WithBoolean("allow_thin",
		mcp.Description("If true, skip section validation for capsule_text"),
	),
)

var deleteToolDef = mcp.NewTool("moss.delete",
	mcp.WithDescription("Soft-delete a capsule. Address by id OR (workspace+name). Can be recovered with include_deleted."),
	mcp.WithString("id",
		mcp.Description("Capsule ID (ULID). Mutually exclusive with workspace+name."),
	),
	mcp.WithString("workspace",
		mcp.Description("Workspace namespace. Required with name."),
	),
	mcp.WithString("name",
		mcp.Description("Capsule name within workspace."),
	),
)

var latestToolDef = mcp.NewTool("moss.latest",
	mcp.WithDescription("Get the most recently updated capsule in a workspace. Quick way to resume work."),
	mcp.WithString("workspace",
		mcp.Description("Workspace namespace (default: 'default')"),
	),
	mcp.WithBoolean("include_text",
		mcp.Description("Include capsule_text in response (default: false for summary)"),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules in lookup"),
	),
)

var listToolDef = mcp.NewTool("moss.list",
	mcp.WithDescription("List capsule summaries in a workspace with pagination. Sorted by updated_at descending."),
	mcp.WithString("workspace",
		mcp.Description("Workspace namespace (default: 'default')"),
	),
	mcp.WithNumber("limit",
		mcp.Description("Max items to return (default: 20, max: 100)"),
	),
	mcp.WithNumber("offset",
		mcp.Description("Skip first N items for pagination"),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules"),
	),
)

var inventoryToolDef = mcp.NewTool("moss.inventory",
	mcp.WithDescription("List capsule summaries across all workspaces with optional filters. Use for discovery and search."),
	mcp.WithString("workspace",
		mcp.Description("Filter by workspace"),
	),
	mcp.WithString("tag",
		mcp.Description("Filter by tag"),
	),
	mcp.WithString("name_prefix",
		mcp.Description("Filter by name prefix (normalized)"),
	),
	mcp.WithNumber("limit",
		mcp.Description("Max items to return (default: 100, max: 500)"),
	),
	mcp.WithNumber("offset",
		mcp.Description("Skip first N items for pagination"),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules"),
	),
)

var exportToolDef = mcp.NewTool("moss.export",
	mcp.WithDescription("Export capsules to a JSONL file for backup or migration."),
	mcp.WithString("path",
		mcp.Description("Export file path. Default: ~/.moss/exports/<workspace>-<timestamp>.jsonl"),
	),
	mcp.WithString("workspace",
		mcp.Description("Filter by workspace. Omit to export all."),
	),
	mcp.WithBoolean("include_deleted",
		mcp.Description("Include soft-deleted capsules"),
	),
)

var importToolDef = mcp.NewTool("moss.import",
	mcp.WithDescription("Import capsules from a JSONL export file."),
	mcp.WithString("path",
		mcp.Required(),
		mcp.Description("Path to JSONL export file"),
	),
	mcp.WithString("mode",
		mcp.Description("Collision handling: 'error' (default, atomic), 'replace' (overwrite), 'rename' (auto-suffix)"),
		mcp.Enum("error", "replace", "rename"),
	),
)

var purgeToolDef = mcp.NewTool("moss.purge",
	mcp.WithDescription("Permanently delete soft-deleted capsules. Irreversible."),
	mcp.WithString("workspace",
		mcp.Description("Filter by workspace. Omit to purge all."),
	),
	mcp.WithNumber("older_than_days",
		mcp.Description("Only purge capsules deleted more than N days ago"),
	),
)
